version: "3.8"

services:
  ssys-employee-manager-pg:
    image: bitnami/postgresql
    container_name: ssys-employee-manager-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: will
      POSTGRESQL_PASSWORD: wi356595
      POSTGRESQL_DATABASE: ssysemployeemanager
    volumes:
      - pg_data:/bitnami/postgresql

  ssys-employee-manager-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssys-employee-manager-app
    environment:
      NODE_ENV: dev
      JWT_SECRET: secretjwtssysemployeemanager
      DATABASE_URL: "postgresql://will:wi356595@ssys-employee-manager-pg:5432/ssysemployeemanager?schema=public"
    ports:
      - "3333:3333"
    depends_on:
      - ssys-employee-manager-pg
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate dev && npm run dev"

volumes:
  pg_data:
